<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Rakushu.Worker-7695d6d4-b0a7-47d9-9831-c10f8ca9ff71</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Rakushu.Application\Rakushu.Application.csproj" />
    <ProjectReference Include="..\..\Rakushu.Infrastructure\Rakushu.Infrastructure.csproj" />
  </ItemGroup>
</Project>
