// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rakushu.Persistence;

#nullable disable

namespace Rakushu.Persistence.Migrations
{
    [DbContext(typeof(RakushuDbContext))]
    [Migration("20260927033934_Add_Curator_Oov_And_Dictionary_Tables")]
    partial class Add_Curator_Oov_And_Dictionary_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rakushu.Domain.Entities.CuratorReview.CuratorReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CuratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("curator_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision");

                    b.Property<string>("EditedMeaning")
                        .HasColumnType("text")
                        .HasColumnName("edited_meaning");

                    b.Property<string>("EditedPos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("edited_pos");

                    b.Property<string>("EditedReading")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("edited_reading");

                    b.Property<string>("EditedTerm")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("edited_term");

                    b.Property<Guid>("OovCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("oov_candidate_id");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.HasKey("Id")
                        .HasName("pk_curator_reviews");

                    b.HasIndex("CuratorId")
                        .HasDatabaseName("ix_curator_reviews_curator_id");

                    b.HasIndex("OovCandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_curator_reviews_oov_candidate_id");

                    b.ToTable("curator_reviews", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.DictionaryEntry.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionTags")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("definition_tags");

                    b.Property<string>("JlptLevel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("MeaningVietnamese")
                        .HasColumnType("text")
                        .HasColumnName("meaning_vietnamese");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reading");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("term");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WordType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("word_type");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_entries");

                    b.HasIndex("Reading")
                        .HasDatabaseName("ix_dictionary_entries_reading");

                    b.HasIndex("Term")
                        .HasDatabaseName("ix_dictionary_entries_term");

                    b.ToTable("dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Feature.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_features");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_features_code");

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.OovCandidate.OovCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("oov_candidate_id");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<string>("ContextSnippet")
                        .HasColumnType("text")
                        .HasColumnName("context_snippet");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedMeaning")
                        .HasColumnType("text")
                        .HasColumnName("suggested_meaning");

                    b.Property<string>("TentativePos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tentative_pos");

                    b.Property<string>("TentativeReading")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tentative_reading");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("term");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_oov_candidates");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_oov_candidates_status");

                    b.HasIndex("Term")
                        .HasDatabaseName("ix_oov_candidates_term");

                    b.ToTable("oov_candidates", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Payment.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_code");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("text")
                        .HasColumnName("qr_code_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_order_code");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_payments_plan_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payments_subscription_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Payment.PaymentTransaction.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gateway");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("RawWebhookData")
                        .HasColumnType("text")
                        .HasColumnName("raw_webhook_data");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_code");

                    b.Property<long?>("SepayId")
                        .HasColumnType("bigint")
                        .HasColumnName("sepay_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<decimal>("TransferAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("transfer_amount");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transfer_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_transactions_payment_id");

                    b.HasIndex("SepayId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_transactions_sepay_id")
                        .HasFilter("sepay_id IS NOT NULL");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Plan.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_code");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Plan.PlanEntitlement.PlanEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<string>("LimitPeriod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("limit_period");

                    b.Property<string>("LimitUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("limit_unit");

                    b.Property<int>("LimitValue")
                        .HasColumnType("integer")
                        .HasColumnName("limit_value");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id")
                        .HasName("pk_plan_entitlements");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("ix_plan_entitlements_feature_id");

                    b.HasIndex("PlanId", "FeatureId")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_entitlements_plan_id_feature_id");

                    b.ToTable("plan_entitlements", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Role.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_title");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.EmailVerificationToken.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_token_user_id");

                    b.ToTable("email_verification_token", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.RefreshToken.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.Subscription.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.Subscription.SubscriptionUsage.SubscriptionUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedValue")
                        .HasColumnType("integer")
                        .HasColumnName("used_value");

                    b.HasKey("Id")
                        .HasName("pk_subscription_usages");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("ix_subscription_usages_feature_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_usages_subscription_id");

                    b.ToTable("subscription_usages", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("Profile", "Rakushu.Domain.Entities.User.User.Profile#Profile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AvatarKey")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("profile_avatar_key");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("profile_full_name");

                            b1.Property<string>("NativeLanguage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("profile_native_language");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.CuratorReview.CuratorReview", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.User.User", "Curator")
                        .WithMany()
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_curator_reviews_users_curator_id");

                    b.HasOne("Rakushu.Domain.Entities.OovCandidate.OovCandidate", "OovCandidate")
                        .WithOne("CuratorReview")
                        .HasForeignKey("Rakushu.Domain.Entities.CuratorReview.CuratorReview", "OovCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_curator_reviews_oov_candidates_oov_candidate_id");

                    b.Navigation("Curator");

                    b.Navigation("OovCandidate");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Payment.Payment", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.Plan.Plan", "Plan")
                        .WithMany("Payments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_plans_plan_id");

                    b.HasOne("Rakushu.Domain.Entities.User.Subscription.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_subscriptions_subscription_id");

                    b.HasOne("Rakushu.Domain.Entities.User.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_user_id");

                    b.Navigation("Plan");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Payment.PaymentTransaction.PaymentTransaction", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.Payment.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transactions_payments_payment_id");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Plan.PlanEntitlement.PlanEntitlement", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.Feature.Feature", "Feature")
                        .WithMany("PlanEntitlements")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_entitlements_features_feature_id");

                    b.HasOne("Rakushu.Domain.Entities.Plan.Plan", "Plan")
                        .WithMany("PlanEntitlements")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_entitlements_plans_plan_id");

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.EmailVerificationToken.EmailVerificationToken", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.User.User", null)
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_token_users_user_id");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.RefreshToken.RefreshToken", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.User.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.Subscription.Subscription", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.Plan.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan_id");

                    b.HasOne("Rakushu.Domain.Entities.User.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.Subscription.SubscriptionUsage.SubscriptionUsage", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.Feature.Feature", "Feature")
                        .WithMany("SubscriptionUsages")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_usages_features_feature_id");

                    b.HasOne("Rakushu.Domain.Entities.User.Subscription.Subscription", "Subscription")
                        .WithMany("SubscriptionUsages")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_usages_subscriptions_subscription_id");

                    b.Navigation("Feature");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.User", b =>
                {
                    b.HasOne("Rakushu.Domain.Entities.Role.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Feature.Feature", b =>
                {
                    b.Navigation("PlanEntitlements");

                    b.Navigation("SubscriptionUsages");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.OovCandidate.OovCandidate", b =>
                {
                    b.Navigation("CuratorReview");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Payment.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Plan.Plan", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PlanEntitlements");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.Role.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.Subscription.Subscription", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SubscriptionUsages");
                });

            modelBuilder.Entity("Rakushu.Domain.Entities.User.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
